# Default values for realtime.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gbaeke/iotaidev
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

env:
  port: 80
  redishost: iotaidev.redis.cache.windows.net
  rediskey: somekey

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 125m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
