apiVersion: v1
kind: Service
metadata:
  name: realtime
  labels:
    app: realtime
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: realtime
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: realtime-app
  labels:
    app: realtime-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: realtime
  template:
    metadata:
      labels:
        app: realtime
    spec:
      containers:
        - name: realtime
          image: gbaeke/iotaidev:latest
          env:
          - name: PORT
            value: "80"
          - name: REDISHOST
            value: "iotaidev.redis.cache.windows.net"
          - name: REDISKEY
            value: ""
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          